debug:
  false
server:
  port:
    8004
  error:
    path:
      /error
    whitelabel:
      enabled:
        false
spring:
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
      
elasticsearch:
    host: localhost
    port: 9200
    username: <username>
    password: <password>

feign:
  client:
    config:
      appsearch:
        defaultRequestHeaders:
          Authorization:"Bearer search-untdq4d62zdka9zq4mkre4vv""